name: Build and Push on oracle-dev

run-name: Build and push image to OCIR on oracle-dev push

on:
  push:
    branches:
      - oracle-dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      # OCI AUTH
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      # IMAGE VARS
      IMAGE_NAME: corrino-devops-repository/llama-stack-oci
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v3

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@d65011bf8c9300e51a98658388a0fb46d1ed54b1 # v1.3.0
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Read version
        id: version
        run: echo "value=$(cat VERSION)" >> "$GITHUB_OUTPUT"

      - name: Build Docker Image
        run: |
          docker build \
            -f containers/Containerfile \
            --build-arg INSTALL_MODE=editable \
            --build-arg DISTRO_NAME=oci \
            -t "${{ env.IMAGE_NAME }}":${{ steps.version.outputs.value }} \
            .

      - name: Tag and Push Docker Image
        env:
          IMAGE_REMOTE: "ord.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/${{ env.IMAGE_NAME }}"
        run: |
          docker tag "${{ env.IMAGE_NAME }}:${{ steps.version.outputs.value }}" "${{ env.IMAGE_REMOTE }}:${{ steps.version.outputs.value }}"
          docker push "${{ env.IMAGE_REMOTE }}:${{ steps.version.outputs.value }}"
